### ISSUE TITLE
Proper Parsing/Writing attributes with namespaces

### ISSUE THREAD

**Issue by kcgolden** [polotek/libxmljs#201]
Hi,

I am trying to read/write attributes from AndroidManifest.xml but the attributes are usually prefixed with 'android:'

Example:
~~~~~~~~
<supports-screens android:xlargeScreens="true" android:largeScreens="true" android:normalScreens="true" android:smallScreens="true" android:resizeable="true" android:anyDensity="true"/>
~~~~~~~~
I can read the attribute with:

xmlDoc.attr('anyDensity').value();

I couldn't find it if I did:

xmlDoc.attr('android:anyDensity').value();

The second option is more explicit so that would be preferable. I also need to be able write new attributes with the 'android:' prefex and I haven't a clue how to do that.

I "think" this is a feature request, if not a bug since we don't seem to be able to have attributes of the form "string:string". However, I am willing to accept the possibility that I'm missing something fundamental and it is possible to do what I desire with libxmljs using some vodoo I have not yet discovered. Can you help me out?

**Comment by benoror** [comment]
Updated the wiki accordingly: https://github.com/polotek/libxmljs/wiki/Attribute#attributenamespace

**Comment by defunctzombie** [comment]
Closing this as I think the namespace method on attribute gets the result needed. If that is not the case we can re-open.
