### ISSUE TITLE
nodejs crashed with SIGSEGV in libxmljs::XmlNode::~XmlNode()

### ISSUE THREAD

**Issue by lanoxx** [polotek/libxmljs#230]
I just got this error when executing my script. I am not sure whats causing it yet. There are only few things I could pull from the crash log:

StacktraceTop:
 libxmljs::XmlNode::~XmlNode() () from /home/user/Code/libxmljs/build/Release/xmljs.node
 libxmljs::XmlElement::~XmlElement() () from /home/user/Code/libxmljs/build/Release/xmljs.node

SegvReason: reading NULL VMA

Any idea?

**Comment by teleological** [comment]
I agree that this looks like #163. Since that issue was corrected by #323, I think this issue can be closed.

**Comment by rc0x03** [comment]
I agree, this issue is pretty likely to be fixed and we can't test it because no tests were provided.
