### ISSUE TITLE
nodejs crashed with SIGSEGV in libxmljs::XmlNamespace::~XmlNamespace()

### ISSUE THREAD

**Issue by lanoxx** [polotek/libxmljs#232]
Here is a similar almost identical version of the show case from the constructor bug. This version segfaults in the destructor instead of the constructor:

    var xml = require('libxmljs');

    var NAMESPACE1 = "http://niceNamespace.org";
    var PREFIX1 = "someThingNice";
    var NAMESPACE2 = "http://interesting.org";
    var PREFIX2 = "interesing";
    var NAMESPACE3 = "http://funnyname.org";
    var PREFIX3 = "funny";

    // Create 20 documents
    for (var i=0; i<20; i++) {
        var doc = xml.Document();
        var rootElement = xml.Element(doc, 'rootElement' + i, '');
        rootElement.defineNamespace(PREFIX1, NAMESPACE1);
        rootElement.defineNamespace(NAMESPACE2);
        rootElement.defineNamespace(PREFIX3, NAMESPACE3);
        rootElement.namespace(PREFIX1, NAMESPACE1);
        doc.root(rootElement);
        // Put 100 child elements into the rootElement
        for (var j = 0; j < 100; j++) {
            var child1Element = xml.Element(doc, 'child1', '');
            child1Element.namespace(PREFIX2, NAMESPACE2);
            rootElement.addChild(child1Element);
            //Put 5 child elements into the second level of each child element
            for(var k = 0; k < 5; k++) {
                var child2Element = xml.Element(doc, 'child2', '');
                child2Element.namespace(PREFIX3, NAMESPACE3);
                child2Element.text("foobar");
                child2Element.attr('tom');
                child1Element.addChild(child2Element);
                var comment = xml.Comment(doc, 'Some short comment.');
                child1Element.addChild(comment);
            }
            child1Element.child(3).remove(); //Remove the third second level child.
        }
        rootElement.child(0).remove(); //ERROR
    }

**Comment by teleological** [comment]
This is different than #163, but it is fixed by #352.

**Comment by defunctzombie** [comment]
closing, future discussions in the PR.
