### ISSUE TITLE
XmlDocument should be subclass of XmlNode

### ISSUE THREAD

**Issue by hildjj** [polotek/libxmljs#272]
This is quite typical in DOMs.  The most important method to get access to is `type()`

Alternately, just add `type`, please, so I can process an entire document with the same recursive code.

**Comment by teleological** [comment]
Added `type()` in #353.

**Comment by defunctzombie** [comment]
Referenced PR merged. Docs need updating.

**Comment by teleological** [comment]
@defunctzombie Docs updated. I think this can be closed out.
