### ISSUE TITLE
Linking issues for libxmljs

### ISSUE THREAD

**Issue by tinganho** [polotek/libxmljs#277]
When I require your library in node 0.11.13 I got this error outputted:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V837AdjustAmountOfExternalAllocatedMemoryEl
  Referenced from: /Users/tinganho/Development/l10ns/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v82V837AdjustAmountOfExternalAllocatedMemoryEl
  Referenced from: /Users/tinganho/Development/l10ns/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: dynamic lookup
```

**Comment by polotek** [comment]
Please use 0.11.14 and let us know if it's still a problem. The 0.11 versions are considered unstable and we're not going to target specific versions. I had trouble installing 0.11.13 as well, but 0.11.14 works fine for me on OS X 10.9. If you still have trouble, please provide your OS information as well. If we don't hear from you, we'll close this in a few days.

**Comment by vgrichina** [comment]
@polotek I have such problem on Node 0.12

**Comment by cycomachead** [comment]
I'm seeing this issue on node 0.12.0 on OS X 10.10, and on Heroku. It wasn't an issue on 0.10.36

**Comment by steegi** [comment]
This issue still seems to be around, but somehow I can only find closed references. Is there still an open issue around this. I am seeing this issue on Mac OS X 10.10 using both node.js 0.12.2 as well as io.js 1.8.1. Thank you.

**Comment by walkermalling** [comment]
Started getting this error on OS X 10.9, Node 0.10.38,  libxmljs 0.14.0
