### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by tcurdt** [polotek/libxmljs#280]
Sorry, for the not very specific issue title but just nothing works as expected:

    var xml = '<?xml version="1.0" encoding="UTF-8"?> \
      <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9  http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> \
    <url> \
      <loc>http://google.com</loc> \
      <lastmod>2010-02-01T02:18:34+00:00</lastmod> \
      <changefreq>daily</changefreq> \
      <priority>1.0</priority> \
    </url> \
    </urlset>';
  
    var libxmljs = require("libxmljs");
    var doc = libxmljs.parseXmlString(xml);
    console.log('doc:', doc);
    var locations = doc.find('//default:loc', { default: 'http://www.sitemaps.org/schemas/sitemap/0.9' });
    console.log('locations:', locations);
    for(var i in locations) {
      console.log('l:', locations[i]);
    }

resulting in:

    doc: { errors: [] }
    locations: [ {} ]
    l: {}

The output does not make sense on so many levels.
`doc` should show more information on the document.
`locations` should show the one child found.
`l` should show the child.

...but this does not seem to work at all.

**Comment by polotek** [comment]
I agree it's confusing. We're open to better object representations. Patches are welcome. But we're not sure when we'll get to this.
