### ISSUE TITLE
Feature: optionally use the installed libxml instead of rebuilding

### ISSUE THREAD

**Issue by tomekwi** [polotek/libxmljs#281]
We have a simple build system – on every tag the repo is checked out and a fresh install is done. This takes ages, as libxml must be recompiled every time. Even though libxml is already installed.on the build server.

Would it be possible to add an option to use the native libxml instead of rebuilding? That behaviour could be triggered by an environment variable, for instance.

**Comment by polotek** [comment]
I hear you. But I think you're dealing with 2 separate issues. Even if you
could use the pre-installed version of libxml2, libxmljs would still need
to build against that. It would take a little less time, bit it would still
be a step. The reason we ship or own libxml2 is we can be assured of the
version and control compatibility. We had lots of problems before with
people linking against different versions of the pre-installed library.

It sounds like the main issue is you don't want to rebuild on every machine
for each release. That's understandable, but you're better off doing a
package deploy to combat that issue. Either build on machine and create a
package, or at least pre-build libxmljs and distribute it. If you're set on
using npm install for deploys, you should consider putting the libxmljs
into version control along with the built bindings. That way npm will skip
it.

I hope this helps. I'm open to configurable builds for people who know the
risks though. If you want to submit a patch, we would take a look. Thanks.

**Comment by defunctzombie** [comment]
What @polotek is all true and we think it is better to ship the library as we are currently doing.

If it is taking "ages" I would suggest getting a better computer :)

**Comment by tomekwi** [comment]
> I'm open to configurable builds for people who know the risks though. If you want to submit a patch, we would take a look. Thanks.

@polotek thanks for the response. I have no experience with building c tools, and very little time at the moment. If any of the two changes, I'll try to help :)
