### ISSUE TITLE
Retrieving enum from XML when matching with .xsd

### ISSUE THREAD

**Issue by Cyberuben** [polotek/libxmljs#285]
I have a .xsd file that specifies a restriction on certain fields, using enumerations. Is it possible to parse the XML file with the .xsd file and returning an object that instead of the strings, returns an integer that matches the string? I can't seem to find it out when reading the /test or /example folder.

**Comment by polotek** [comment]
I'm not sure what you're referring to. Could you point to the feature in
libxml2 that does what you're suggesting?

**Comment by Cyberuben** [comment]
I think I have misunderstood the concept of enumerations in XML and confused it with i.e. enumerators in C++. An enum is just a descriptive representation of a number, to make things more descriptive than "if(type == 1)". I expected enumerations in XML to be the same, it turns out they are not.

**Comment by polotek** [comment]
Okay. If you come to a legitimate issue in your usage, please open another ticket. Thanks.
