### ISSUE TITLE
//grandchild only returns one element (first)

### ISSUE THREAD

**Issue by monkeyfdude** [polotek/libxmljs#292]
Deleted/Edited this..please see my last comment

**Comment by polotek** [comment]
Please submit some code that demonstrates this problem.

**Comment by monkeyfdude** [comment]
var libxmljs = require("libxmljs");
var xml =  '<?xml version="1.0" encoding="UTF-8"?>' +
           '<root>' +
               '<child foo="bar">' +
                   '<grandchild baz="fizbuzz">grandchild content</grandchild>' +
               '</child>' +
               '<child foo="bar">' +
                   '<grandchild baz="fizbuzz">grandchild2 content</grandchild>' +
               '</child>' +
               '<sibling>with content!</sibling>' +
           '</root>';

var xmlDoc = libxmljs.parseXmlString(xml);
console.log(xmlDoc.toString())

// xpath queries
var gchild = xmlDoc.get('//grandchild');

console.log(gchild.toString());  // prints "grandchild content"

var children = xmlDoc.root().childNodes();
var child = children[0];

console.log(child.attr('foo').value()); // prints "bar"

**Comment by defunctzombie** [comment]
Without code we cannot help diagnose this issue.

**Comment by polotek** [comment]
There is code here. It just doesn't make sense. @monkeyfdude, I think
something is being lost in the formatting of your xml file.

**Comment by monkeyfdude** [comment]
Following code is what I thought gave me error. Please note it could be my lack of understanding of Xpath Queries. May be its not a bug....please help me understand.

For the xml below, I expect two grandchild elements but I get only one. How do I get two for

console.log(gchild.text());  // prints "grandchild content"

```
var libxmljs = require("libxmljs");
var xml =  '<?xml version="1.0" encoding="UTF-8"?>' +
           '<root>' +
               '<child foo="bar">' +
                   '<grandchild baz="fizbuzz">grandchild content</grandchild>' +
               '</child>' +
               '<child foo="bar">' +
                   '<grandchild baz="fizbuzz2">grandchild2 content</grandchild>' +
               '</child>' +

               '<sibling>with content!</sibling>' +
           '</root>';

var xmlDoc = libxmljs.parseXml(xml);

// xpath queries
var gchild = xmlDoc.get('//grandchild');

console.log(gchild.text());  // prints "grandchild content"

var children = xmlDoc.root().childNodes();
var child = children[0];

console.log(child.attr('foo').value()); // prints "bar"
```

**Comment by monkeyfdude** [comment]
do you guys think this is not an issue?

**Comment by defunctzombie** [comment]
It isn't that we think it is not an issue, it is that neither I nor @polotek have time to dig into it currently :(

For us, this module is mostly in coasting mode so we are happy to look at additional contributors or PRs for review.

**Comment by polotek** [comment]
@monkeyfdude I apologize because I didn't look at this code closely until now. The only problem here is you're using the wrong method. Instead of `xmlDoc.get('//grandchild');` you want `xmlDoc.find('//grandchild');`. The `find()` returns an array of all xpath results. The `get()` method does the same xpath search but then returns only the first element. It's just a shortcut for when you only expect one element in your document.

Also keep in mind that when you use `find()`, you'll get an array and not a node or element. So your call to `gchild.text()` will fail. That is also to be expected.

Sorry for the confusion here. Check out the wiki to confirm the api methods you need. Let us know if you run into other issues.

**Comment by monkeyfdude** [comment]
Thank you. I realized that and I closed the issue as well.
 Thank you again
