### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by meonkeys** [polotek/libxmljs#309]
I'm trying to build the Meteor package [`csats/meteor-npm-libxmljs`](https://github.com/csats/meteor-npm-libxmljs), which pulls in libxmljs 0.14.0 as a dependency. I'm not sure where to file this issue or even what's going on, but I gotta start somewhere.

    local$ meteor admin get-machine os.windows.x86_32

    Microsoft Windows [Version 6.0.6002]
    Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

    C:\Windows\system32> meteor publish-for-arch csats:libxmljs@1.0.0
    bin\\npm-cli.js"
    "install"
    npm ERR! node v0.10.36
    npm ERR! npm  v2.7.3
    npm ERR! code ELIFECYCLE

    npm ERR! libxmljs@0.14.0 install: `node-gyp rebuild`
    npm ERR! Exit status 7
    npm ERR!
    npm ERR! Failed at the libxmljs@0.14.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the libxmljs package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls libxmljs
    npm ERR! There is likely additional logging output above.

    => Errors while initializing project:

    While building package csats:libxmljs:
    error: couldn't install npm packages from npm-shrinkwrap

Any ideas?

**Comment by defunctzombie** [comment]
Please try to reproduce a failing build with only libxmljs module and not other modules involved.

Also make sure you have the required build dependencies installed. Please see the readme.

**Comment by meonkeys** [comment]
Fair 'nuff. Will do.

**Comment by jackkav** [comment]
+1
