### ISSUE TITLE
Crash on MacOS X 

### ISSUE THREAD

**Issue by Changdao** [polotek/libxmljs#322]
##Environment

    Darwin Jmpro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
    iojs v2.1.0

#Thread backtrace:
frame #0: 0x00007fff8c4c1286 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff91fb242f libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff8725bb53 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff87223c39 libsystem_c.dylib`__assert_rtn + 321
    frame #4: 0x00000001010f2059 bson.node`node::ObjectWrap::Ref(this=<unavailable>) + 65 at node_object_wrap.h:88
    frame #5: 0x0000000103505548 xmljs.node`libxmljs::XmlElement::New(v8::FunctionCallbackInfo<v8::Value> const&) [inlined] libxmljs::XmlElement::XmlElement(node=0x000000010150fa88) + 11 at xml_element.cc:455
    frame #6: 0x000000010350553d xmljs.node`libxmljs::XmlElement::New(v8::FunctionCallbackInfo<v8::Value> const&) [inlined] libxmljs::XmlElement::XmlElement(node=0x000000010150fa88) at xml_element.cc:456
    frame #7: 0x000000010350553d xmljs.node`libxmljs::XmlElement::New(args=0x00007fff5fbfed08) + 389 at xml_element.cc:49
    frame #8: 0x000000010017363e node`v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 158
    frame #9: 0x000000010019f9f6 node`v8::internal::Builtin_HandleApiCallConstruct(int, v8::internal::Object**, v8::internal::Isolate*) + 758
    frame #10: 0x00000febdc0060bb
    frame #11: 0x00000febdc015221
    frame #12: 0x00000febdc7685ea
    frame #13: 0x00000febdc76832d
    frame #14: 0x00000febdc014b35
    frame #15: 0x00000febdc766ae7
    frame #16: 0x00000febdc014b35
    frame #17: 0x00000febdc766799
    frame #18: 0x00000febdc01aca6
    frame #19: 0x00000febdc161298
    frame #20: 0x00000febdc014b35
    frame #21: 0x00000febdc446222
    frame #22: 0x00000febdc4453b1
    frame #23: 0x00000febdc4445a6
    frame #24: 0x00000febdc444277
    frame #25: 0x00000febdc444163
    frame #26: 0x00000febdc44337a
    frame #27: 0x00000febdc015320
    frame #28: 0x00000febdc0140d1
    frame #29: 0x00000001002adca8 node`v8::internal::Invoke(bool, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 984
    frame #30: 0x000000010015e7b1 node`v8::Function::Call(v8::Handle<v8::Value>, int, v8::Handle<v8::Value>*) + 193
    frame #31: 0x000000010061dc05 node`node::MakeCallback(node::Environment*, v8::Handle<v8::Value>, v8::Handle<v8::Function>, int, v8::Handle<v8::Value>*) + 639
    frame #32: 0x0000000100624d06 node`node::CheckImmediate(uv_check_s*) + 98
    frame #33: 0x000000010068a61d node`uv__run_check + 33
    frame #34: 0x00000001006868dd node`uv_run + 284
    frame #35: 0x00000001006246fc node`node::Start(int, char**) + 442
    frame #36: 0x0000000100000d34 node`start + 52
(lldb) 
* thread #1: tid = 0x90a26, 0x00007fff8c4c1286 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff8c4c1286 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff91fb242f libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff8725bb53 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff87223c39 libsystem_c.dylib`__assert_rtn + 321
    frame #4: 0x00000001010f2059 bson.node`node::ObjectWrap::Ref(this=<unavailable>) + 65 at node_object_wrap.h:88
    frame #5: 0x0000000103505548 xmljs.node`libxmljs::XmlElement::New(v8::FunctionCallbackInfo<v8::Value> const&) [inlined] libxmljs::XmlElement::XmlElement(node=0x000000010150fa88) + 11 at xml_element.cc:455
    frame #6: 0x000000010350553d xmljs.node`libxmljs::XmlElement::New(v8::FunctionCallbackInfo<v8::Value> const&) [inlined] libxmljs::XmlElement::XmlElement(node=0x000000010150fa88) at xml_element.cc:456
    frame #7: 0x000000010350553d xmljs.node`libxmljs::XmlElement::New(args=0x00007fff5fbfed08) + 389 at xml_element.cc:49
    frame #8: 0x000000010017363e node`v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 158
    frame #9: 0x000000010019f9f6 node`v8::internal::Builtin_HandleApiCallConstruct(int, v8::internal::Object**, v8::internal::Isolate*) + 758
    frame #10: 0x00000febdc0060bb
    frame #11: 0x00000febdc015221
    frame #12: 0x00000febdc7685ea
    frame #13: 0x00000febdc76832d
    frame #14: 0x00000febdc014b35
    frame #15: 0x00000febdc766ae7
    frame #16: 0x00000febdc014b35
    frame #17: 0x00000febdc766799
    frame #18: 0x00000febdc01aca6
    frame #19: 0x00000febdc161298
    frame #20: 0x00000febdc014b35
    frame #21: 0x00000febdc446222
    frame #22: 0x00000febdc4453b1
    frame #23: 0x00000febdc4445a6
    frame #24: 0x00000febdc444277
    frame #25: 0x00000febdc444163
    frame #26: 0x00000febdc44337a
    frame #27: 0x00000febdc015320
    frame #28: 0x00000febdc0140d1
    frame #29: 0x00000001002adca8 node`v8::internal::Invoke(bool, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 984
    frame #30: 0x000000010015e7b1 node`v8::Function::Call(v8::Handle<v8::Value>, int, v8::Handle<v8::Value>*) + 193
    frame #31: 0x000000010061dc05 node`node::MakeCallback(node::Environment*, v8::Handle<v8::Value>, v8::Handle<v8::Function>, int, v8::Handle<v8::Value>*) + 639
    frame #32: 0x0000000100624d06 node`node::CheckImmediate(uv_check_s*) + 98
    frame #33: 0x000000010068a61d node`uv__run_check + 33
    frame #34: 0x00000001006868dd node`uv_run + 284
    frame #35: 0x00000001006246fc node`node::Start(int, char**) + 442
    frame #36: 0x0000000100000d34 node`start + 52

**Comment by defunctzombie** [comment]
Can't do much with this and without a failing example not sure much can be done.
