### ISSUE TITLE
[Question] Getting error information?

### ISSUE THREAD

**Issue by blakeembrey** [polotek/libxmljs#327]
Is there a way to extract more meaningful information from XSD validation? Perhaps the schema issue or the node that occured using XPath?

**Comment by scaryguy** [comment]
@blakeembrey , looks like you didn't see this at the wiki:

```js
assert.equal(xmlDocInvalid.validationErrors.length, 2);
console.log(xmlDocInvalid.validationErrors);
```
it prints something like this:

```js
[ { [Error: Element 'comment': Character content other than whitespace is not allowed because the content type is 'element-only'.
  ] domain: 17, code: 1843, level: 2, column: 0, line: 2 },
  { [Error: Element 'comment': Missing child element(s). Expected is one of ( author, content ).
  ] domain: 17, code: 1871, level: 2, column: 0, line: 2 } ]
```

**Comment by blakeembrey** [comment]
@scaryguy I did and I'm using what I can from that. But it doesn't give me the property that failed, for instance. Just the text position and other meta information. Are you saying there's a way to pull something out of that?

**Comment by scaryguy** [comment]
That should be related to your XSD schema. For it to give proper errors, your XSD should force it to do. 

For example here is an example from my app:

```console
1) VAST generator should create ad block:
     Error: Error: Element 'AdTtle': This element is not expected. Expected is ( AdTitle ).

      at test/vast/vast_unit.js:47:11
```

This error is produced because my XSD schema includes this line:

```xml
 <xs:element type="xs:string" name="AdTitle"/>
```

I hope it helps.

**Comment by blakeembrey** [comment]
I understand that (I'll admit I haven't played with XSD too much), but then the only way to get the information from this is to parse the error string itself. What about nested elements in the XSD validation? I didn't recall seeing the XPath to the error location, which is the information I really want to parse from the message. Of course, this could all be a limitation of the libxml which is why I'm asking.

**Comment by defunctzombie** [comment]
I don't know enough about libxml itself to answer this unfortunately. If you do learn more please feel free (and obliged ;)) to update the wiki with your learnings!

I am closing this out since this support issue seems to have some assistance and there is no particular code issue here yet.
