### ISSUE TITLE
Fail to get when xml string contains xmlns

### ISSUE THREAD

**Issue by tuananh** [polotek/libxmljs#338]
Using the sample [xml here](http://pastebin.com/raw.php?i=dc9nGGiB)

With `xmlns="http://www.hotelbeds.com/schemas/2005/06/messages"`, it will fails. Deleting that part at root, it will work as expected. I really have no idea why it behaves like that.

    var xmlDoc = libxmljs.parseXml(xml)
    var gchild = xmlDoc.get('/HotelValuedAvailRS/AuditData/ProcessTime')
    console.log(gchild.text())

**Comment by hildjj** [comment]
See the [docs](https://github.com/polotek/libxmljs/wiki/Element#elementfindxpath-namespaces):

    var f = xml.parseXmlString("<foo xmlns='urn:foo'><bar/></foo>");
    f.get('f:bar', {f: 'urn:foo'}).toString();  // returns '<bar/>'

**Comment by tuananh** [comment]
@hildjj is there anyway to make it work without passing the namespace?

**Comment by hildjj** [comment]
I don't understand what you want.  <foo xmlns='urn:foo'> is a **completely** different element name than <foo/>, semantically.  The namespace is a part of the name.  You're thinking of "xmlns" as if it is an attribute; that approach will lead you to increasing amounts of heartache over time.

**Comment by tuananh** [comment]
@hildjj my use case is like this, i have a js object with xpath; and as xml coming in, it will transform that object with data from the xml so it will fail because i didn't pass the namespace.

Do you know any work around this?

**Comment by battlesnake** [comment]
@tuananh: You could use a regexp to remove /xmlns="[^"]*"/g from the xml source before parsing it, as a quick and dirty hack

**Comment by defunctzombie** [comment]
Closing since it appears to be a usage error not a library error.

**Comment by abimelex** [comment]
You can try to use different xPath selectors, in my case it helped to refer to the local-name, but it was only a single tag:
`
result.get("//*[local-name(.)='MyTagName']")`

**Comment by tuananh** [comment]
yeah , it's more of usage issue. i'm ending up doing dirty hack by removing it.
