### ISSUE TITLE
Unhandled rejection Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by tuananh** [polotek/libxmljs#340]
`npm i` works but when running application, the following error returned

`Unhandled rejection Error: Could not locate the bindings file. Tried:....`

Tried with Ubuntu 14.04 and `libxmljs` 0.14.3

**Comment by defunctzombie** [comment]
Seems like `npm i` did not finish or had other errors. Also make sure you installed with the same version you are running your app with (if you have multiple versions of node installed).

Closing because this is likely an environment/config issue on your machine.
