### ISSUE TITLE
Module version mismatch. Expected 47, got 46.

### ISSUE THREAD

**Issue by Zig1375** [polotek/libxmljs#344]
NodeJS 5.0.0
Got an error:
Module version mismatch. Expected 47, got 46.

**Comment by Zig1375** [comment]
Why closed?

**Comment by defunctzombie** [comment]
Because there is no helpful information here to debug this nor do I think you have done any googling around for how to resolve this issue. You upgraded node without rebuilding the module.

**Comment by soops** [comment]
I've upgraded Node and rebuilt the module, yet I am still recieving this error.

**Comment by soops** [comment]
Before you ask, I have attempted to rebuild the module manually using `node-gyp` and I have deleted my `node-modules` folder and reinstalled. I've also reinstalled Node and NPM. My Node version is 4.4.7, and my NPM version is 3.10.5. I still get this error after all of this.
