### ISSUE TITLE
CSS to XPath?

### ISSUE THREAD

**Issue by rc0x03** [polotek/libxmljs#345]
My project depends on CSS selector to XPath conversion. I've got it implemented in javascript but I'd like to write a solid c++ version. It accepts any combination of CSS, XPath, CSS with XPath, and XPath with CSS expressions. Since it's type agnostic, my idea would be to use it for `Element.find` by default. That way libxmljs would have native support for both without having the user specify which. If I were to implement this and create a pull request would it be an acceptable feature in terms of the project scope or is it something you would like to keep separate?

**Comment by defunctzombie** [comment]
It would be outside of the project scope to include this since it is not a libxml feature. However, we can reference it in the wiki so others can find it as they read through the documentation.
