### ISSUE TITLE
namespace(ns) : wrong return type

### ISSUE THREAD

**Issue by bhamon** [polotek/libxmljs#356]
The doc states that:
> element.namespace(ns)
> > Set the element's namespace to ns
> > args ns - a Namespace object
> > returns - the element object

But the actual code returns the new namespace (see https://github.com/polotek/libxmljs/blob/master/src/xml_node.cc#L83):
```cpp
return info.GetReturnValue().Set(node->get_namespace());
```

This prevents chain calls like the following:
```javascript
let ns = root.defineNamespace('n1', 'http://my.ns.com');
root
  .node('foo').namespace(ns)
    .node('bar', 'test').namespace(ns)
  .parent()
.parent();
```

**Comment by teleological** [comment]
Fixed in #357
