### ISSUE TITLE
update contributor emails

### ISSUE THREAD

**Issue by defunctzombie** [polotek/libxmljs#374]
@rc0x03 @teleological please make sure your commits have a valid email address associated with them which can be used to reach you. This is important in the event of security disclosures or follow up emails not on github. If both of you have valid emails on your commits then this issue can be closed.

Thanks!

**Comment by teleological** [comment]
I can confirm.

**Comment by rc0x03** [comment]
I've updated my global git settings to include my email address.

**Comment by defunctzombie** [comment]
Thanks!
