### ISSUE TITLE
Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by scarolan** [polotek/libxmljs#377]
I can't seem to install or use node-gyp.  Here's the output when I try to start up a Hubot locally.  This is on OSX, with node installed via homebrew:

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/hubot-gordon/node_modules/hubot-wolfram/node_modules/wolfram/node_modules/libxmljs
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/hubot-gordon/npm-debug.log
```

**Comment by defunctzombie** [comment]
Sounds like an issue on your system. Would be helpful if you provided some information about what you have tried to do to debug this.

**Comment by jarodms6** [comment]
Same. I'm on Windows 7. Fresh install of  Visual Studio 2013

Trying:
npm install gulp-cordova-bump

7996 verbose stack Error: libxmljs@0.14.3 install: `node-gyp rebuild`
7996 verbose stack Exit status 1
7996 verbose stack     at EventEmitter.<anonymous> (C:\DevSoft\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
7996 verbose stack     at emitTwo (events.js:87:13)
7996 verbose stack     at EventEmitter.emit (events.js:172:7)
7996 verbose stack     at ChildProcess.<anonymous> (C:\DevSoft\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
7996 verbose stack     at emitTwo (events.js:87:13)
7996 verbose stack     at ChildProcess.emit (events.js:172:7)
7996 verbose stack     at maybeClose (internal/child_process.js:818:16)
7996 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
7997 verbose pkgid libxmljs@0.14.3
7998 verbose cwd C:\Dev\Projects\my-project
7999 error Windows_NT 6.1.7601
8000 error argv "C:\\DevSoft\\nodejs\\node.exe" "C:\\DevSoft\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-cordova-bump"
8001 error node v4.2.2
8002 error npm  v2.14.7
8003 error code ELIFECYCLE
8004 error libxmljs@0.14.3 install: `node-gyp rebuild`
8004 error Exit status 1
8005 error Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
8005 error This is most likely a problem with the libxmljs package,
8005 error not with npm itself.
8005 error Tell the author that this fails on your system:
8005 error     node-gyp rebuild
8005 error You can get their info via:
8005 error     npm owner ls libxmljs
8005 error There is likely additional logging output above.
