### ISSUE TITLE
Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by magician11** [polotek/libxmljs#379]
I keep getting an error when trying to install my modules. I've tried different versions of node and updated all the packages on Ubuntu.

````
> libxmljs@0.14.3 install /home/apps/slash-commands-for-slack/node_modules/libxmljs
> node-gyp rebuild

make: Entering directory `/home/apps/slash-commands-for-slack/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
../vendor/libxml/parser.c: In function ‘xmlParseInNodeContext’:
../vendor/libxml/parser.c:13492:9: warning: pointer targets in passing argument 1 of ‘xmlFindCharEncodingHandler’ differ in signedness [-Wpointer-sign]
         hdlr = xmlFindCharEncodingHandler(doc->encoding);
         ^
In file included from ../vendor/libxml/include/libxml/parser.h:809:0,
                 from ../vendor/libxml/include/libxml/globals.h:18,
                 from ../vendor/libxml/include/libxml/threads.h:35,
                 from ../vendor/libxml/include/libxml/xmlmemory.h:218,
                 from ../vendor/libxml/parser.c:46:
../vendor/libxml/include/libxml/encoding.h:175:2: note: expected ‘const char *’ but argument is of type ‘const xmlChar *’
  xmlFindCharEncodingHandler (const char *name);
  ^
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
../vendor/libxml/xpath.c: In function ‘xmlXPathNodeCollectAndTest’:
../vendor/libxml/xpath.c:12401:28: warning: comparison between ‘xmlElementType’ and ‘xmlXPathTypeVal’ [-Wenum-compare]
       } else if (cur->type == type) {
                            ^
../vendor/libxml/xpath.c:12402:13: warning: comparison between ‘xmlXPathTypeVal’ and ‘enum <anonymous>’ [-Wenum-compare]
    if (type == XML_NAMESPACE_DECL)
             ^
In file included from ../vendor/libxml/xpath.c:185:0:
../vendor/libxml/xpath.c: At top level:
../vendor/libxml/trionan.c:218:1: warning: ‘trio_is_negative’ defined but not used [-Wunused-function]
 trio_is_negative
 ^
../vendor/libxml/xpath.c: In function ‘xmlXPathCastNumberToString’:
../vendor/libxml/xpath.c:2900:7: warning: array subscript is above array bounds [-Warray-bounds]
   work[buffersize - 1] = 0;
       ^
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
../vendor/libxml/xpointer.c: In function ‘xmlXPtrNewRangeNodePoint’:
../vendor/libxml/xpointer.c:451:21: warning: comparison between ‘xmlElementType’ and ‘enum <anonymous>’ [-Wenum-compare]
     if (start->type != XPATH_POINT)
                     ^
  AR(target) Release/obj.target/vendor/libxml/xml.a
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: g++: Command not found
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 127
make: Leaving directory `/home/apps/slash-commands-for-slack/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v5.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-71-generic
gyp ERR! command "/root/.nvm/versions/node/v5.4.0/bin/node" "/root/.nvm/versions/node/v5.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/apps/slash-commands-for-slack/node_modules/libxmljs
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON slash-commands-for-slack@1.0.0 No repository field.
npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/root/.nvm/versions/node/v5.4.0/bin/node" "/root/.nvm/versions/node/v5.4.0/bin/npm" "install" "freshbooks"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
````

**Comment by defunctzombie** [comment]
Please make sure you have install the compilation dependencies for node-gyp, you are missing `g++` as per the error log.

**Comment by sujithma** [comment]
I keep getting an error when trying to install my modules.

> libxmljs@0.14.3 install /home/ionic/node_modules/libxmljs
> node-gyp rebuild

make: Entering directory `/home/ionic/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
../vendor/libxml/parser.c: In function ‘xmlParseInNodeContext’:
../vendor/libxml/parser.c:13492:9: warning: pointer targets in passing argument 1 of ‘xmlFindCharEncodingHandler’ differ in signedness [-Wpointer-sign]
         hdlr = xmlFindCharEncodingHandler(doc->encoding);
         ^
In file included from ../vendor/libxml/include/libxml/parser.h:809:0,
                 from ../vendor/libxml/include/libxml/globals.h:18,
                 from ../vendor/libxml/include/libxml/threads.h:35,
                 from ../vendor/libxml/include/libxml/xmlmemory.h:218,
                 from ../vendor/libxml/parser.c:46:
../vendor/libxml/include/libxml/encoding.h:175:2: note: expected ‘const char *’ but argument is of type ‘const xmlChar *’
  xmlFindCharEncodingHandler (const char *name);
  ^
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
../vendor/libxml/xpath.c: In function ‘xmlXPathNodeCollectAndTest’:
../vendor/libxml/xpath.c:12401:28: warning: comparison between ‘xmlElementType’ and ‘xmlXPathTypeVal’ [-Wenum-compare]
       } else if (cur->type == type) {
                            ^
../vendor/libxml/xpath.c:12402:13: warning: comparison between ‘xmlXPathTypeVal’ and ‘enum <anonymous>’ [-Wenum-compare]
    if (type == XML_NAMESPACE_DECL)
             ^
In file included from ../vendor/libxml/xpath.c:185:0:
../vendor/libxml/xpath.c: At top level:
../vendor/libxml/trionan.c:218:1: warning: ‘trio_is_negative’ defined but not used [-Wunused-function]
 trio_is_negative
 ^
../vendor/libxml/xpath.c: In function ‘xmlXPathCastNumberToString’:
../vendor/libxml/xpath.c:2900:7: warning: array subscript is above array bounds [-Warray-bounds]
   work[buffersize - 1] = 0;
       ^
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
../vendor/libxml/xpointer.c: In function ‘xmlXPtrNewRangeNodePoint’:
../vendor/libxml/xpointer.c:451:21: warning: comparison between ‘xmlElementType’ and ‘enum <anonymous>’ [-Wenum-compare]
     if (start->type != XPATH_POINT)
                     ^
  AR(target) Release/obj.target/vendor/libxml/xml.a
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
In file included from ../src/libxmljs.h:7:0,
                 from ../src/libxmljs.cc:7:
../node_modules/nan/nan.h:592:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:593:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:598:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:598:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:603:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:604:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:609:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:609:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory `/home/sujith/Codetok/Projects/uptour_ionic/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ionic/node_modules/libxmljs
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
- abbrev@1.0.7 node_modules/abbrev
- ansi@0.3.1 node_modules/ansi
- array-index@1.0.0 node_modules/array-index
- block-stream@0.0.9 node_modules/block-stream
lru-cache@2.7.3 node_modules/lru-cache -> node_modules/cli/node_modules/minimatch/node_modules/lru-cache
sigmund@1.0.1 node_modules/sigmund -> node_modules/cli/node_modules/minimatch/node_modules/sigmund
- code-point-at@1.0.0 node_modules/code-point-at
- delegates@1.0.0 node_modules/delegates
- are-we-there-yet@1.1.2 node_modules/are-we-there-yet
- fstream@1.0.9 node_modules/fstream
- minimatch@3.0.0 node_modules/gulp-sass/node_modules/glob/node_modules/minimatch
- glob@7.0.3 node_modules/gulp-sass/node_modules/glob
- minimatch@0.3.0 node_modules/gulp-sass/node_modules/globule/node_modules/glob/node_modules/minimatch
- glob@3.2.11 node_modules/gulp-sass/node_modules/globule/node_modules/glob
- object-assign@3.0.0 node_modules/gulp-sass/node_modules/gulp-util/node_modules/object-assign
- lodash@2.4.2 node_modules/gulp-sass/node_modules/lodash
- minimatch@0.2.14 node_modules/gulp-sass/node_modules/minimatch
- globule@0.2.0 node_modules/gulp-sass/node_modules/globule
- gaze@1.0.0 node_modules/gulp-sass/node_modules/gaze
- nan@2.3.5 node_modules/gulp-sass/node_modules/nan
- node-sass@3.7.0 node_modules/gulp-sass/node_modules/node-sass
- object-assign@4.1.0 node_modules/gulp-sass/node_modules/object-assign
- source-map@0.5.6 node_modules/gulp-sass/node_modules/source-map
- vinyl-sourcemaps-apply@0.2.1 node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply
- has-unicode@2.0.0 node_modules/has-unicode
- invert-kv@1.0.0 node_modules/invert-kv
- is-fullwidth-code-point@1.0.0 node_modules/is-fullwidth-code-point
- lcid@1.0.0 node_modules/lcid
- lodash._baseslice@4.0.0 node_modules/lodash._baseslice
- lodash._basetostring@4.12.0 node_modules/lodash.pad/node_modules/lodash._basetostring
- lodash._basetostring@4.12.0 node_modules/lodash.padend/node_modules/lodash._basetostring
- lodash._basetostring@4.12.0 node_modules/lodash.padstart/node_modules/lodash._basetostring
- lodash.tostring@4.1.3 node_modules/lodash.tostring
- lodash.padstart@4.5.0 node_modules/lodash.padstart
- lodash.padend@4.5.0 node_modules/lodash.padend
- lodash.pad@4.4.0 node_modules/lodash.pad
- gauge@1.2.7 node_modules/gauge
- minimatch@2.0.10 node_modules/node-gyp/node_modules/glob/node_modules/minimatch
- glob@4.5.3 node_modules/node-gyp/node_modules/glob
- minimatch@1.0.0 node_modules/node-gyp/node_modules/minimatch
- nopt@3.0.6 node_modules/nopt
- npmlog@2.0.4 node_modules/npmlog
- os-tmpdir@1.0.1 node_modules/os-tmpdir
- osenv@0.1.3 node_modules/osenv
- path-array@1.0.1 node_modules/path-array
- pseudomap@1.0.2 node_modules/pseudomap
- glob@6.0.4 node_modules/sass-graph/node_modules/glob
- lodash@4.13.1 node_modules/sass-graph/node_modules/lodash
- window-size@0.1.4 node_modules/sass-graph/node_modules/window-size
- string-width@1.0.1 node_modules/string-width
- cliui@3.2.0 node_modules/sass-graph/node_modules/cliui
- yargs@3.32.0 node_modules/sass-graph/node_modules/yargs
- tar@2.2.1 node_modules/tar
- yallist@2.0.0 node_modules/yallist
- async-foreach@0.1.3 node_modules/async-foreach
- cross-spawn-async@2.2.4 node_modules/cross-spawn-async
- lru-cache@4.0.1 node_modules/cross-spawn-async/node_modules/lru-cache
- in-publish@2.0.0 node_modules/in-publish
- node-gyp@3.3.1 node_modules/node-gyp
- os-locale@1.4.0 node_modules/os-locale
- sass-graph@2.1.1 node_modules/sass-graph
- wrap-ansi@2.0.0 node_modules/wrap-ansi
- y18n@3.2.1 node_modules/y18n
ionic-base@0.0.1 /home/ionic
`-- gulp-sass@0.7.3  invalid
  `-- node-sass@0.9.3
    `-- mocha@1.18.2
      `-- glob@3.2.3
        `-- minimatch@0.2.14
          +-- lru-cache@2.7.3 
          `-- sigmund@1.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionic/npm-debug.log
